### ISSUE TITLE
v0.1

### ISSUE THREAD

**Issue by zoli** [limetext/lime-qml#28]
Tracking issues on all repositories related to v0.1
### backend:
- [ ] https://github.com/limetext/backend/issues/107 Sidebar tree navigation
- [ ] https://github.com/limetext/backend/issues/105 Goto anything quick panel list backend bits
- [ ] https://github.com/limetext/backend/issues/106 Goto anything: list files
- [x] https://github.com/limetext/backend/issues/103 Set a default syntax and colour scheme on start
### commands:
- [x] https://github.com/limetext/commands/issues/4 move bugs
- [x] https://github.com/limetext/commands/issues/5 prompt_save_as
### sublime
- [x] https://github.com/limetext/sublime/issues/4 Move the view tests into the backend
- [ ] https://github.com/limetext/sublime/issues/10 invalid backref number
### qml:
- [x] https://github.com/limetext/lime-qml/issues/21 move up down
- [x] https://github.com/limetext/lime-qml/issues/29 Deleting line
- [x] https://github.com/limetext/lime-qml/issues/33 Save As dialog
- [ ] https://github.com/limetext/lime-qml/issues/3 QML dynamic status bar
- [ ] #37 frontend.Show
- [ ] #38 frontend.VisibleRegion

There are more issues mostly on editing in qml frontend which will be added later.
##

**Comment by vyegres** [comment]
maybe add to list "support  golang 1.6"?

**Comment by zoli** [comment]
I don't think it's really necessary for v0.1.
For go 1.6 support some parts of gopy and qml-go should change and IMO we have more important issues right now.

**Comment by zoli** [comment]
Moved this to a project [here](https://github.com/limetext/lime-qml/projects/1).
